logging:
  level:
    root: INFO
    org:
      apache: WARN
      springframework: WARN
      kurento:
        tutorial: INFO
# OUTPUT
# Terminal color output; one of [ALWAYS, DETECT, NEVER]
spring:
  output:
    ansi:
      enabled: detect
  # ----------------------------------------
  # WEB PROPERTIES
  # ----------------------------------------

  # EMBEDDED SERVER CONFIGURATION
server:
  port: @demo.port@
  context-path: /v-charts
  ssl:
    key-alias: kurento-selfsigned
    key-store-type: JKS
    key-store: classpath:keystore.jks
    key-store-password: kurento